#!/usr/bin/env bash
set -Eeuo pipefail

rm -rf ./dist/*

yarn test

yarn build

git add ./dist

# doErr() {
#   echo '\e[91mDIST not committed. Exiting'
#   exit 1
# }

# git diff --quiet ./dist || doErr